<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
	'UpdraftPlus_CopyCom_API' => $vendorDir.'/copy/API.php',
	'UpdraftPlus_CopyCom_API_WordPress' => $vendorDir.'/copy/API.php'
);
